### ISSUE TITLE
蓝牙有问题

### ISSUE THREAD

**Issue by ghost** [bywwh/device_xiaomi_aries_mkl#1]
Mi2SC，没有可用的配对设备，也没有 smartlock ，手环废了……

从昨天开始尝试刷机，试了很多 ROM，各种问题，现在真的心灰意冷。韦大的 CM 是问题最少的，但蓝牙不正常，还有据说不能刷入 gapps（我还没试），希望尽快修复吧，虽然知道韦大挺辛苦的……

如果可以能不能写一个简单的教程，放在 Wiki 上，让我们自己手动编译调试……

**Comment by Guanhang** [comment]
别逗了，秋大的aosp才最正常，6.0很好
